"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _SearchDepth:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SearchDepthEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SearchDepth.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SEARCH_DEPTH_UNSPECIFIED: _SearchDepth.ValueType  # 0
    SEARCH_DEPTH_STANDARD: _SearchDepth.ValueType  # 1
    SEARCH_DEPTH_DEEP: _SearchDepth.ValueType  # 2
    SEARCH_DEPTH_RESEARCH: _SearchDepth.ValueType  # 3
    SEARCH_DEPTH_FAST: _SearchDepth.ValueType  # 4

class SearchDepth(_SearchDepth, metaclass=_SearchDepthEnumTypeWrapper): ...

SEARCH_DEPTH_UNSPECIFIED: SearchDepth.ValueType  # 0
SEARCH_DEPTH_STANDARD: SearchDepth.ValueType  # 1
SEARCH_DEPTH_DEEP: SearchDepth.ValueType  # 2
SEARCH_DEPTH_RESEARCH: SearchDepth.ValueType  # 3
SEARCH_DEPTH_FAST: SearchDepth.ValueType  # 4
Global___SearchDepth: _TypeAlias = SearchDepth  # noqa: Y015

class _ResearchDepth:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ResearchDepthEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ResearchDepth.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    RESEARCH_DEPTH_UNSPECIFIED: _ResearchDepth.ValueType  # 0
    RESEARCH_DEPTH_S: _ResearchDepth.ValueType  # 1
    RESEARCH_DEPTH_M: _ResearchDepth.ValueType  # 2
    RESEARCH_DEPTH_L: _ResearchDepth.ValueType  # 3
    RESEARCH_DEPTH_XL: _ResearchDepth.ValueType  # 4

class ResearchDepth(_ResearchDepth, metaclass=_ResearchDepthEnumTypeWrapper): ...

RESEARCH_DEPTH_UNSPECIFIED: ResearchDepth.ValueType  # 0
RESEARCH_DEPTH_S: ResearchDepth.ValueType  # 1
RESEARCH_DEPTH_M: ResearchDepth.ValueType  # 2
RESEARCH_DEPTH_L: ResearchDepth.ValueType  # 3
RESEARCH_DEPTH_XL: ResearchDepth.ValueType  # 4
Global___ResearchDepth: _TypeAlias = ResearchDepth  # noqa: Y015

class _SearchOuptutType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SearchOuptutTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SearchOuptutType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SEARCH_OUTPUT_UNSPECIFIED: _SearchOuptutType.ValueType  # 0
    SEARCH_OUTPUT_SEARCH_RESULTS: _SearchOuptutType.ValueType  # 1
    SEARCH_OUTPUT_SOURCED_ANSWER: _SearchOuptutType.ValueType  # 2
    SEARCH_OUTPUT_STRUCTURED: _SearchOuptutType.ValueType  # 3

class SearchOuptutType(_SearchOuptutType, metaclass=_SearchOuptutTypeEnumTypeWrapper): ...

SEARCH_OUTPUT_UNSPECIFIED: SearchOuptutType.ValueType  # 0
SEARCH_OUTPUT_SEARCH_RESULTS: SearchOuptutType.ValueType  # 1
SEARCH_OUTPUT_SOURCED_ANSWER: SearchOuptutType.ValueType  # 2
SEARCH_OUTPUT_STRUCTURED: SearchOuptutType.ValueType  # 3
Global___SearchOuptutType: _TypeAlias = SearchOuptutType  # noqa: Y015

@_typing.final
class SearchRequest(_message.Message):
    """///////////////
    // SEARCH /////
    ///////////////
    """

    DESCRIPTOR: _descriptor.Descriptor

    QUERY_FIELD_NUMBER: _builtins.int
    DEPTH_FIELD_NUMBER: _builtins.int
    OUTPUT_TYPE_FIELD_NUMBER: _builtins.int
    STRUCTURED_OUTPUT_SCHEMA_FIELD_NUMBER: _builtins.int
    INCLUDE_IMAGES_FIELD_NUMBER: _builtins.int
    FROM_DATE_FIELD_NUMBER: _builtins.int
    TO_DATE_FIELD_NUMBER: _builtins.int
    SETTINGS_FIELD_NUMBER: _builtins.int
    EXCLUDE_DOMAINS_FIELD_NUMBER: _builtins.int
    INCLUDE_DOMAINS_FIELD_NUMBER: _builtins.int
    INCLUDE_INLINE_CITATIONS_FIELD_NUMBER: _builtins.int
    REQUEST_INFO_FIELD_NUMBER: _builtins.int
    MAX_RESULTS_FIELD_NUMBER: _builtins.int
    RESEARCH_DEPTH_FIELD_NUMBER: _builtins.int
    query: _builtins.str
    depth: Global___SearchDepth.ValueType
    output_type: Global___SearchOuptutType.ValueType
    structured_output_schema: _builtins.str
    """JSON string representing the structured output schema"""
    include_images: _builtins.bool
    from_date: _builtins.str
    """String representing an ISO 8601 date (YYYY-MM-DD)"""
    to_date: _builtins.str
    """String representing an ISO 8601 date (YYYY-MM-DD)"""
    include_inline_citations: _builtins.bool
    max_results: _builtins.int
    research_depth: Global___ResearchDepth.ValueType
    @_builtins.property
    def settings(self) -> Global___SearchSettings: ...
    @_builtins.property
    def exclude_domains(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def include_domains(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def request_info(self) -> Global___RequestInfo: ...
    def __init__(
        self,
        *,
        query: _builtins.str = ...,
        depth: Global___SearchDepth.ValueType = ...,
        output_type: Global___SearchOuptutType.ValueType = ...,
        structured_output_schema: _builtins.str = ...,
        include_images: _builtins.bool = ...,
        from_date: _builtins.str = ...,
        to_date: _builtins.str = ...,
        settings: Global___SearchSettings | None = ...,
        exclude_domains: _abc.Iterable[_builtins.str] | None = ...,
        include_domains: _abc.Iterable[_builtins.str] | None = ...,
        include_inline_citations: _builtins.bool = ...,
        request_info: Global___RequestInfo | None = ...,
        max_results: _builtins.int = ...,
        research_depth: Global___ResearchDepth.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["request_info", b"request_info", "settings", b"settings"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["depth", b"depth", "exclude_domains", b"exclude_domains", "from_date", b"from_date", "include_domains", b"include_domains", "include_images", b"include_images", "include_inline_citations", b"include_inline_citations", "max_results", b"max_results", "output_type", b"output_type", "query", b"query", "request_info", b"request_info", "research_depth", b"research_depth", "settings", b"settings", "structured_output_schema", b"structured_output_schema", "to_date", b"to_date"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SearchRequest: _TypeAlias = SearchRequest  # noqa: Y015

@_typing.final
class SearchSettings(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    AGENT_FIELD_NUMBER: _builtins.int
    POLICY_FIELD_NUMBER: _builtins.int
    RESPONSE_FORMATTER_FIELD_NUMBER: _builtins.int
    agent: _builtins.str
    """The name of the agent to use for the search"""
    policy: _builtins.str
    """The name of the policy to use for the search"""
    response_formatter: _builtins.str
    """The name of the response formatter to use for the search"""
    def __init__(
        self,
        *,
        agent: _builtins.str = ...,
        policy: _builtins.str = ...,
        response_formatter: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["agent", b"agent", "policy", b"policy", "response_formatter", b"response_formatter"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SearchSettings: _TypeAlias = SearchSettings  # noqa: Y015

@_typing.final
class RequestInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REQUEST_ID_FIELD_NUMBER: _builtins.int
    ORGANIZATION_ID_FIELD_NUMBER: _builtins.int
    request_id: _builtins.str
    organization_id: _builtins.str
    def __init__(
        self,
        *,
        request_id: _builtins.str = ...,
        organization_id: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["organization_id", b"organization_id", "request_id", b"request_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RequestInfo: _TypeAlias = RequestInfo  # noqa: Y015

@_typing.final
class SearchResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ANSWER_FIELD_NUMBER: _builtins.int
    SEARCH_RESULTS_FIELD_NUMBER: _builtins.int
    TRACES_FIELD_NUMBER: _builtins.int
    STRUCTURED_ANSWER_FIELD_NUMBER: _builtins.int
    BRAIN_VERSION_FIELD_NUMBER: _builtins.int
    SETTINGS_FIELD_NUMBER: _builtins.int
    answer: _builtins.str
    traces: _builtins.str
    structured_answer: _builtins.str
    brain_version: _builtins.str
    @_builtins.property
    def search_results(self) -> _containers.RepeatedCompositeFieldContainer[Global___SearchResult]: ...
    @_builtins.property
    def settings(self) -> Global___SearchSettings: ...
    def __init__(
        self,
        *,
        answer: _builtins.str = ...,
        search_results: _abc.Iterable[Global___SearchResult] | None = ...,
        traces: _builtins.str = ...,
        structured_answer: _builtins.str = ...,
        brain_version: _builtins.str = ...,
        settings: Global___SearchSettings | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["settings", b"settings"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["answer", b"answer", "brain_version", b"brain_version", "search_results", b"search_results", "settings", b"settings", "structured_answer", b"structured_answer", "traces", b"traces"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SearchResponse: _TypeAlias = SearchResponse  # noqa: Y015

@_typing.final
class TextResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    URL_FIELD_NUMBER: _builtins.int
    CONTENT_FIELD_NUMBER: _builtins.int
    FAVICON_FIELD_NUMBER: _builtins.int
    RELEVANCY_SCORE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    url: _builtins.str
    content: _builtins.str
    favicon: _builtins.str
    relevancy_score: _builtins.float
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        url: _builtins.str = ...,
        content: _builtins.str = ...,
        favicon: _builtins.str = ...,
        relevancy_score: _builtins.float | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_relevancy_score", b"_relevancy_score", "relevancy_score", b"relevancy_score"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_relevancy_score", b"_relevancy_score", "content", b"content", "favicon", b"favicon", "name", b"name", "relevancy_score", b"relevancy_score", "url", b"url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__relevancy_score: _TypeAlias = _typing.Literal["relevancy_score"]  # noqa: Y015
    _WhichOneofArgType__relevancy_score: _TypeAlias = _typing.Literal["_relevancy_score", b"_relevancy_score"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__relevancy_score) -> _WhichOneofReturnType__relevancy_score | None: ...

Global___TextResult: _TypeAlias = TextResult  # noqa: Y015

@_typing.final
class ImageResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    URL_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    url: _builtins.str
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        url: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "url", b"url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ImageResult: _TypeAlias = ImageResult  # noqa: Y015

@_typing.final
class SearchResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TEXT_RESULT_FIELD_NUMBER: _builtins.int
    IMAGE_RESULT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def text_result(self) -> Global___TextResult: ...
    @_builtins.property
    def image_result(self) -> Global___ImageResult: ...
    def __init__(
        self,
        *,
        text_result: Global___TextResult | None = ...,
        image_result: Global___ImageResult | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["image_result", b"image_result", "result", b"result", "text_result", b"text_result"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["image_result", b"image_result", "result", b"result", "text_result", b"text_result"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_result: _TypeAlias = _typing.Literal["text_result", "image_result"]  # noqa: Y015
    _WhichOneofArgType_result: _TypeAlias = _typing.Literal["result", b"result"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_result) -> _WhichOneofReturnType_result | None: ...

Global___SearchResult: _TypeAlias = SearchResult  # noqa: Y015
